import { BlockNumber } from '@aztec/foundation/branded-types';

// Re-export L2 block number constants with proper BlockNumber type
// Note: The generated constants are plain numbers, but we provide typed versions here
import { INITIAL_L2_BLOCK_NUM as INITIAL_L2_BLOCK_NUM_RAW } from './constants.gen.js';

// Typescript-land-only constants
export const SPONSORED_FPC_SALT = BigInt(0);

// Autogenerated constants loaded from noir-land
export * from './constants.gen.js';

/**
 * The initial L2 block number (typed as BlockNumber).
 * This is the first block number in the Aztec L2 chain.
 */
export const INITIAL_L2_BLOCK_NUM_TYPED: BlockNumber = BlockNumber(INITIAL_L2_BLOCK_NUM_RAW);
